# -*- coding: utf-8 -*-
"""jpmorgan_filecsv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UNr0dWyoSCnhj4k1KEmLtNcsVkmxNofm
"""

import pandas as pd

file_list=["1Q21_Earnings_Supplement.xlsx","2Q21_Earnings_Supplement.xlsx","3Q21_Earnings_Supplement.xlsx","4Q21_Earnings_Supplement.xlsx",
           "1q22-earnings-supplement.xlsx","2Q22-Earnings-Supplement.xlsx","3Q22_Earnings_Supplement.xlsx","4q22-earnings-supplement-xls.xlsx",
           "1q23-earnings-supplement.xlsx","2q23-earnings-supplement.xlsx","3q23-earnings-supplement.xlsx","4q23-earnings-supplement.xlsx",
           "1Q24_Earnings_Supplement.xlsx","2q24-earnings-supplement.xlsx","3q24-earnings-supplement.xlsx","4q24-earnings-supplement.xlsx",
          "1q25-earnings-supplement.xlsx" ]

def data_extraction_jpmorgan(file_list,sheet_name):
  df_list = []
  quarters=[]
  for item in file_list:
    df_page2 = pd.read_excel(item, sheet_name=sheet_name, header=None, usecols="B:F", skiprows=6)
    header_rows = df_page2.iloc[1:4, 1:5]
    col_header = header_rows.fillna(method='ffill', axis=1).apply(lambda row: ' '.join(row.dropna().astype(str)), axis=1)
    quarter_label = df_page2.iloc[0, 4]
    final_columns = ['Quarters'] + [f"{quarter_label} - {h}" for h in col_header]
    line_items = df_page2.iloc[2:39, 0:3].apply(lambda row: ' '.join(row.dropna().astype(str)).strip(), axis=1)
    data_values = df_page2.iloc[2:39, 4]
    data_values_cleaned = data_values.replace(r'\((.*?)\)', r'-\1', regex=True).astype(str).str.replace(',', '').str.replace('$', '', regex=False).str.replace('%', '', regex=False).str.strip()
    data_values_numeric = pd.to_numeric(data_values_cleaned, errors='coerce')
    df_list.append(data_values_numeric)
    quarters.append(final_columns[1][:4])

  lista=pd.DataFrame(df_list)
  lista.columns=line_items
  lista.index=quarters
  df_results=lista.dropna(axis=1)
  df_results.head()
  return df_results

df_results=data_extraction_jpmorgan(file_list,"Page 2")

df_results.info()

df_results.head()

df_results.to_csv("jpmorgan_cleaned_summary.csv", index=True)

df_results.to_excel("jpmorgan_cleaned_summary.xlsx", index=True)